---
- name: Run rancher admin node
  hosts: rancher_admin
  become: true
  become_user: root
  roles:
    - role: setup
    - role: docker/setup
    - role: rancher/run-rancher
  vars:
    # https://hub.docker.com/r/rancher/rancher/tags
    rancher_version: "v2.11.3"
    rancher_docker_image: "rancher/rancher:{{ rancher_version }}"
    rancher_data_dir: "/opt/rancher"
    rancher_compose_file: docker-compose.yml
    rancher_container_name: rancher
    rancher_http_port: 80
    rancher_https_port: 443
