---
- name: Setup rke2 k3s nodes
  hosts: kube_control_plane,kube_node
  become: true
  become_user: root
  roles:
    - role: setup
    - role: install-tools
  vars:
    # https://hub.docker.com/r/rancher/rancher/tags
    rancher_version: "v2.11.3"
    # https://github.com/containerd/nerdctl/releases
    nerdctl_version: "2.1.6"
    # https://github.com/etcd-io/etcd/releases
    etcd_version: "3.5.21"
    # https://www.suse.com/suse-rancher/support-matrix/all-supported-versions
    # https://github.com/rancher/rke2/tags
    # https://kubernetes.io/releases/
    kubectl_version: "v1.32.9"
