---
control_plane_endpoint: 10.0.0.1  # e.g. keepalived virtual_ip
pod_network_cidr: 10.244.0.0/16
service_network_cidr: 10.96.0.0/12
kube_api_endpoint: control.plane.endpoint
kube_api_endpoint_port: 6443

# https://www.suse.com/suse-rancher/support-matrix/all-supported-versions
# https://github.com/rancher/rke2/tags
# https://kubernetes.io/releases/
kubectl_version: "v1.33.5"
# https://github.com/containerd/nerdctl/releases
nerdctl_version: "2.1.6"
# https://github.com/etcd-io/etcd/releases
etcd_version: "3.5.21"

cilium_version: "1.17.6"  # https://github.com/cilium/cilium/releases
flannel_version: "latest"  # https://github.com/flannel-io/flannel/releases
calico_version: "v3.30.2"  # https://github.com/projectcalico/calico/releases
cilium_namespace: kube-system
cilium_helm_repo: https://helm.cilium.io/
cilium_helm_chart: cilium/cilium
replacement_status: false  # true: without kube-proxy

kube_control_plane:
  control_plane01:
    host_name: control_plane01
    address: 192.168.10.1
    internal_address: 10.0.0.5
  control_plane02:
    host_name: control_plane02
    address: 192.168.10.2
    internal_address: 10.0.0.6
kube_node:
  node01:
    host_name: node01
    address: 192.168.10.3
    internal_address: 10.0.0.8
  node02:
    host_name: node02
    address: 192.168.10.4
    internal_address: 10.0.0.9
  node03:
    host_name: node03
    address: 192.168.10.5
    internal_address: 10.0.0.10
  node04:
    host_name: node04
    address: 192.168.10.6
    internal_address: 10.0.0.11
haproxy:
  proxy01:
    host_name: proxy01
    address: 192.168.10.7
    internal_address: 10.0.0.12
    keepalived_role: master
  proxy02:
    host_name: proxy02
    address: 192.168.10.8
    internal_address: 10.0.0.13
    keepalived_role: backup
rancher_admin:
  rancher_admin01:
    host_name: rancher_admin01
    address: 192.168.10.9
    internal_address: 10.0.0.14
