---
- name: Include create-cluster tasks
  ansible.builtin.import_tasks: create-cluster.yml
  run_once: true

- name: Include get-token tasks
  ansible.builtin.import_tasks: get-token.yml
  run_once: true
