---
- name: Include create-cluster tasks
  ansible.builtin.import_tasks: create-cluster.yml
  when: inventory_hostname == ansible_play_hosts_all[0]

- name: Include get-token tasks
  ansible.builtin.import_tasks: get-token.yml
  when: inventory_hostname == ansible_play_hosts_all[0]
